// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_demo.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6eN0ldIqikuSBGhEsyNDrc4U8KmRIgu8',
    appId: '1:220959690754:android:76b20c18191c154d98171b',
    messagingSenderId: '220959690754',
    projectId: 'flutter-bloc-cubit-344ef',
    storageBucket: 'flutter-bloc-cubit-344ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDusQljTXbskAOZWB3Yzfmi-XLLmUiWzI0',
    appId: '1:220959690754:ios:32dcb78bc4b5d07c98171b',
    messagingSenderId: '220959690754',
    projectId: 'flutter-bloc-cubit-344ef',
    storageBucket: 'flutter-bloc-cubit-344ef.firebasestorage.app',
    androidClientId: '220959690754-mgi0iiruvat5uq10652s6qqkmr3u2pmm.apps.googleusercontent.com',
    iosClientId: '220959690754-29jb6jnn2si1a2nmrn7h5034b7gp54n1.apps.googleusercontent.com',
    iosBundleId: 'com.jasmine.flutterBlocCubit.demo',
  );
}
