// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6eN0ldIqikuSBGhEsyNDrc4U8KmRIgu8',
    appId: '1:220959690754:android:615ccc22d72a5b5098171b',
    messagingSenderId: '220959690754',
    projectId: 'flutter-bloc-cubit-344ef',
    storageBucket: 'flutter-bloc-cubit-344ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDusQljTXbskAOZWB3Yzfmi-XLLmUiWzI0',
    appId: '1:220959690754:ios:762a24abcd0e449e98171b',
    messagingSenderId: '220959690754',
    projectId: 'flutter-bloc-cubit-344ef',
    storageBucket: 'flutter-bloc-cubit-344ef.firebasestorage.app',
    iosClientId: '220959690754-jsd8bfcoi4rhj8jncfa2rgm7kd2a92ae.apps.googleusercontent.com',
    iosBundleId: 'com.jasmine.flutterBlocCubit',
  );
}